#!/usr/bin/env sh

echo 'Passes arguments through to $MC/mach'

CURRENTDIR=`pwd`

export GAIADIR=~/code/mozilla/gaia
export MOZCONFIG=$CURRENTDIR/mozconfig-b2gdroid
export MOZTTDIR=~/code/mozilla/moztt

cd $MC

if ! test -d ./gcc/bin; then
	mkdir -p ./gcc/bin
	ln -s `which gcc` gcc
	ln -s `which g++` g++
fi

set -e

$MC/mach $@
